'use strict';
const l1Element=document.querySelector('.li1');
const l2Element=document.querySelector('.li2');
const l3Element=document.querySelector('.li3');
const content1=' 1';
const content2=' 2';
const content3=' 3';
l1Element.innerHTML=content1;
l2Element.innerHTML=content2;
l3Element.innerHTML=content3;
